# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Release Check
# This workflow runs Bazel build and test when triggered by tag creation.

name: Bazel Build & Test baselibs (with host toolchain GCC12.2)
on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
      - 'release-*' # Triggers on release tags like release-1.0.0

permissions:
  contents: write

jobs:
  build_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Bazel build baselibs targets
        run: |
          bazel build --config bl-x86_64-linux -- //score/...
  build_target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Setup QNX License
        env:
          SCORE_QNX_LICENSE: ${{ secrets.SCORE_QNX_LICENSE }}
        run: |
          mkdir -p /opt/score_qnx/license
          echo "${SCORE_QNX_LICENSE}" | base64 --decode > /opt/score_qnx/license/licenses
      - name: Bazel build baselibs targets
        # Currently, only a subset of targets are building with QNX toolchain
        # due to various issues such as https://github.com/eclipse-score/baselibs/issues/28
        env:
          SCORE_QNX_USER: ${{ secrets.SCORE_QNX_USER }}
          SCORE_QNX_PASSWORD: ${{ secrets.SCORE_QNX_PASSWORD }}
        run: |
          bazel build --config bl-x86_64-qnx --credential_helper=*.qnx.com=${{ github.workspace }}/.github/tools/qnx_credential_helper.py -- \
            //score/... \
            -//score/os/mocklib/qnx:secpolev_mock \
            -//score/os/qnx:pci_safety \
            -//score/language/futurecpp/tests:jthread_test \
            -//score/language/futurecpp/tests:math_test \
            -//score/mw/log/rust:log
      - name: Cleanup QNX License
        if: always()
        run: rm -rf /opt/score_qnx
  test_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Bazel test baselibs targets
        run: |
          bazel test --config bl-x86_64-linux //score/... -- \
          -//score/language/safecpp/aborts_upon_exception:abortsuponexception_toolchain_test \
          -//score/containers:dynamic_array_test
      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
      - name: Bazel coverage baselibs targets
        run: |
          # Run every test target
          for target in $(bazel query 'tests(attr(name, "unit_test_suite_host", //...:*))'); do
            # Replace leading // with bazel-bin path, and ':' with '/'
            out="$(bazel info bazel-bin)/${target#//}"
            out="${out/://}"
            "$out"
          done
          # Collect coverage data
          lcov --capture \
            --directory="$(bazel info bazel-bin)/score/" \
            --output-file=cpp_coverage.info \
            --gcov-tool="$(bazel info execution_root)/external/score_toolchains_gcc++gcc+gcc_toolchain_gcc/bin/x86_64-unknown-linux-gnu-gcov" \
            --base-directory="$(bazel info workspace)" \
            --branch-coverage \
            --ignore-errors=mismatch \
            --exclude="*/external/*" \
            --ignore-errors gcov
          # Generate HTML report
          genhtml cpp_coverage.info \
            -o=cpp_coverage \
            --show-details \
            --legend \
            --function-coverage \
            --branch-coverage
        shell: bash
      - name: Create archive of test report
        run: |
          mkdir -p artifacts
          find bazel-testlogs/score/ -name 'test.xml' -print0 | xargs -0 -I{} cp --parents {} artifacts/
          cp -r cpp_coverage artifacts/
          zip -r ${{ github.event.repository.name }}_coverage_report.zip artifacts/
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_coverage_report.zip
          path: ${{ github.event.repository.name }}_coverage_report.zip
      - name: Upload release asset (attach ZIP to GitHub Release)
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: ${{ github.event.repository.name }}_coverage_report.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_verification:
    runs-on: ubuntu-latest
    needs: [build_host, build_target, test_host]
    if: always() && (needs.build_host.result == 'failure' || needs.build_target.result == 'failure' || needs.test_host.result == 'failure')
    steps:
      - name: Remove release and tag (if exists)
        uses: nikhilbadyal/ghaction-rm-releases@v0.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PATTERN: ${{ github.ref_name }}
